### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by svx** [plone/sphinxtheme.plone#67]
Currently running ``make html` with papyrus gives the following error:
```
 Exception occurred:
  File "/home/svx/Projects/plone/papyrus/eggs/sphinxtheme.plone-0.5.7-py2.7.egg/sphinxtheme/plone/plone_basic/layout.html", line 262, in block "footer"
    LANGUAGES: {% if theme_doc_languages|length > 0 %}['{{ theme_doc_languages|join("', '", attribute='lang_code') }}']{% else %}[]{% endif %},
TypeError: do_join() got an unexpected keyword argument 'attribute'
```
@loechel maybe do you have time to have a look ?

Thanks !

**Comment by svx** [comment]
@loechel as workaround I removed the line:
```
LANGUAGES: {% if theme_doc_languages|length > 0 %}['{{ theme_doc_languages|join("', '", attribute='lang_code') }}']{% else %}[]{% endif %},
```
from the js template, since we are only using _en_ this is working.

So for the moment that is OK, but we should fix that as soon as someone has time :)

**Comment by loechel** [comment]
I have looked into it, but could not reproduce it, any hints how to raise this error?

**Comment by svx** [comment]
This was wit papyrus branch 5.1

Sphinx = 1.6.7

I did not try with the latest Sphinx version, yet.

If you follow the steps in https://github.com/plone/papyrus/blob/5.1/docs/install.rst the error occurs by running ``make html``.

First it runs and after some time it stops with this error message.

**Comment by svx** [comment]
@loechel @polyester 
We still have theme errors, this is with Sphinx 1.7.2
```
Theme error:
An error happened in rendering the page CHANGES.
Reason: TypeError("do_join() got an unexpected keyword argument 'attribute'",)
Makefile:67: recipe for target 'html-en' failed
make: *** [html-en] Error 2
```

**Comment by svx** [comment]
Again fixed by removing:
```
LANGUAGES: {% if theme_doc_languages|length > 0 %}['{{ theme_doc_languages|join("', '", attribute='lang_code') }}']{% else %}[]{% endif %},
```

**Comment by loechel** [comment]
@svx OK I have traced it down.
The Problem is not sphinxtheme.plone it are the version pins on papyrus, which pulled Jinja2 2.5.5 and not 2.10 

I did fix that in papyrus
