### ISSUE TITLE
Does this theme installable?

### ISSUE THREAD

**Issue by geohuz** [plone/sphinxtheme.plone#73]
I just downloaded the newest plone5 and feel the default theme is no good for technical documentation, (source code highlighting...), so I followed the instructions on this repository, but nothing happened, and I can't find the conf.py file to change. BTW, is there anyway I can use the read the doc theme (RTD theme) for my document?

**Comment by loechel** [comment]
This is a theme for sphinx generated documentation, not for Plone itself. It uses the corporate design of plone.org for its documentation.

By the way. Plone is a fantastic Content Management System, but if you just write documentation Sphinx-Docs or MK-Docs propably would be a much better fit for you.
