### ISSUE TITLE
Gitter Link still available on the front-end of the docs section of Plone.org that needs to be removed!

### ISSUE THREAD

**Issue by rohnsha0** [plone/sphinxtheme.plone#75]
![image](https://user-images.githubusercontent.com/86848116/186946489-f1ab07fc-b6d4-4acd-9295-957517fedaa9.png)

**Comment by polyester** [comment]
deployed, but takes a while to show due to caching

**Comment by rohnsha0** [comment]
> deployed, but takes a while to show due to caching

Cool!
And on this topic... We made several more changes on main plone.org website (a few weeks ago) but they weren't deployed yet and changes aren't visible to date!
